### ISSUE TITLE
能给个测试账号吗？

### ISSUE THREAD

**Issue by zhubinchen** [mengkeer/xbsz-Objc#1]
我想体验一下，注册了发现还要教务网授权。你能给我一个账号吗？🙏

**Comment by mengkeer** [comment]
这套授权登陆的程序是我大四写的，当时用的我自己的账号，但是我现在毕业了，所以我的账号也用不了了，我也没有其它的账号了

另外由于我2年没试过授权登陆了，所以可能现在能不能授权成功也是一回事，因为只要教务网服务端做了啥变动，我的代码将就没用了

**Comment by zhubinchen** [comment]
好的，谢谢你的回复哈
